order:
  info:
    status:
      change:
        rocketmq:
          topic: order_info_status_change_rocketmq_topic
  main:
    status:
      change:
        rocket:
          topic: order_status_change_rocketmq_topic
  ordersync:
    async:
      order:
        status:
          topic: ordersync_async_order_status_topic


rocketmq:
  #生产环境
  name-server: rocketmq-1169816974305218562-001.cmcdcp-cli.svc.cluster.local:9876
  #本地测试环境
#  name-server: 10.71.164.32:9876
  #预发环境
#  name-server: rocketmq-1206847778214694914-002.cmcdcp-cli.svc.cluster.local:9876
  producer:
        group: cmsc_ummp_buy_group

orderfile: /home/app/ummp-gateway/order.txt
#orderfile: /Users/hujun/Desktop/order.log

cmic:
  forward:
    api:
      url: https://gr-proxyservice.prod.com:32908/grproxy/jump/rightsJump
      key: coczijiEqUan66$%Yi~!@#$treasure